<?php include "config.php"?>
<?php include "header.blade.php"?>
<?php include "hero.blade.php"?>
<?php include "about.blade.php"?>
<?php include "whyus.blade.php"?>
<?php include "counts.blade.php"?>
<?php include "services.blade.php"?>
<?php include "portfolio.blade.php"?>
<?php include "team.blade.php"?>
<?php include "faq.blade.php"?>
<?php include "contact.blade.php"?> 
<?php include "footer.blade.php"?>